# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calucate Network Exposure
#' 
#' 
show_network_exposure <- function(dyad_ties_file, y_file) {
    invisible(.Call(`_NetworkExposure_show_network_exposure`, dyad_ties_file, y_file))
}

